account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from account import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('simple/', views.simple_view, name='simple'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('activate/<uidb64>/<token>', views.ActivateAccountView.as_view(), name='activate'),
    path('users-cart/', views.users_cart, name='users_cart')

]

beerproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store'),),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),


    path('reset_password/', PasswordResetView.as_view(
        html_email_template_name = 'register/password_reset_email_msg.html',
        subject_template_name = 'register/password_reset_subject_msg.txt'
    ), name='reset_password'),
    path('reset_password_sent/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carts/urls.py
from django.urls import path
from carts import views

app_name = "carts"

urlpatterns = [
               path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
               path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
               path('cart_remove/', views.CartRemove.as_view(), name='cart_remove'),
               ]

store/urls.py
from django.urls import path
from store import views

app_name = "store"

urlpatterns = [
               path('', views.StoreListView.as_view(), name='main'),
               path('search/', views.CategoryListView.as_view(), name='search'),
               path('category/<slug:category_slug>/', views.CategoryListView.as_view(), name='category'),
               path('item/<slug:item_slug>/', views.show_item, name='item'),
               ]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ru">
<head>
    <link rel="icon" type="image/png" href="{% static 'images/favico.png' %}"/>

    <meta charset="UTF-8">
    <title>
      {% block title %}

      {% endblock title %}
    </title>
    {% block styles %}
        {# Здесь будут стили дочерних шаблонов #}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>

    </style>
    
</head>
<body class="ms-5 me-5">
    <div class="navbar mb-5 menu">
        <a class="navbar-brand ms-5" href="{% url 'store:main' %}">
            <img id="icon_store" src="{% static 'images/icon.png' %}" alt=""> Крафт мания
        </a>
        <nav class="dropdown ms-5">
          <button class="btn btn-basecolor dropdown-toggle" type="button" id="dropdownCategoryMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            Категории
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownCategoryMenuButton">
              <li><a class="dropdown-item" href="/">Все</a></li>
              <li><a class="dropdown-item" href="{% url 'store:category' 'pivo' %}">Пиво</a></li>
              <li><a class="dropdown-item" href="{% url 'store:category' 'sidr' %}">Сидр</a></li>
              <li><a class="dropdown-item" href="{% url 'store:category' 'razlivnoe-pivo' %}">Разливное пиво</a></li>
          </ul>
        </nav>
        <nav class="ms-5">
            <form method="GET" action="{% url 'store:search' %}">
                <div class="search_align">
                    <input type="text" name="q" placeholder="Поиск..." class="search_child"/>
                    <button class="btn btn-basecolor search_child">Найти</button>
                </div>
            </form>
        </nav>

        <nav class="ms-5 card p-1">
            <div id="cart-items-container">
                {% include 'carts/includes/basket_bar.html' %}
            </div>
        </nav>
        <nav><!--<nav class="ms-auto me-5">-->
            {% include 'login_bar.html' %}
        </nav>


    </div>
    {% block notification %}
        {# Здесь будут включены шаблоны уведомлений через инклюд #}
    {% endblock %}
    {% block category %}

    {% endblock category %}
    <div class="container">
        <div class="row justify-content-start">
            <div class="col-3">
                {% block filters %}
                {% endblock filters %}
            </div>

            <div class="col">
                <div>
                    {% block content %}
                    {% endblock content %}
                </div>

                    {% block paginator %}
                    {% endblock paginator %}
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-ajax.js' %}"></script>

</body>
</html>

templates/login_bar.html
{% load static %}
{% block styles %}
        <link rel="stylesheet" href="{% static 'css/logbar.css' %}">
{% endblock %}


{% if not request.user.is_authenticated %}
    <a href="{% url 'account:login' %}" class="btn btn-basecolor"> Авторизация </a>
{% else %}
    
        <form method="post" action="{% url 'account:logout' %}">
        {% csrf_token %}
    <div class="greeting-user">
    <div>
        <p class="mt-3 pgreeting">Здравствуйте, <a href="#{#{%url 'contacts' %}#}">{{request.user}}</a></p>
    </div>
    <div>
        <button type="submit" class="btn btn-basecolor login-out">Выход</button> 
    </div>
    </div>
    </form>
{% endif %}