beerproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store'),),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),


    path('reset_password/', PasswordResetView.as_view(
        html_email_template_name = 'register/password_reset_email_msg.html',
        subject_template_name = 'register/password_reset_subject_msg.txt'
    ), name='reset_password'),
    path('reset_password_sent/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carts/urls.py
from django.urls import path
from carts import views

app_name = "carts"

urlpatterns = [
               path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
               path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
               path('cart_remove/', views.CartRemove.as_view(), name='cart_remove'),
               ]

store/urls.py
from django.urls import path
from store import views

app_name = "store"

urlpatterns = [
               path('', views.StoreListView.as_view(), name='main'),
               path('search/', views.CategoryListView.as_view(), name='search'),
               path('category/<slug:category_slug>/', views.CategoryListView.as_view(), name='category'),
               path('item/<slug:item_slug>/', views.show_item, name='item'),
               ]

store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=150, verbose_name='название бренда')
    description = models.TextField(verbose_name='описание бренда', null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Название бренда'
        verbose_name_plural = 'Названия брендов'

    
class BeerStyle(models.Model):
    name = models.CharField(max_length=150, verbose_name='стиль напитка')
    description = models.TextField(verbose_name='описание стиля напитка', null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Стиль напитка'
        verbose_name_plural = 'Стили Напитков'

class VolumeNormQs(models.QuerySet):

    def normalize_value(self):
        if self:
            # print('VALUES_FROM MYMANAGER', self.values)
            new_qs = dict()
            for item in self.values():
                # print('INITIAL_DICT_ITEMS', item)
                if item['value'] < 1:
                    new_qs[item['id']]= item['value'].normalize()
                else:
                    new_qs[item['id']]=int(item['value'])
            return new_qs

class VolumeNormManager(models.Manager.from_queryset(VolumeNormQs)):
    pass

class Volume(models.Model):
    value = models.DecimalField(max_digits=5, decimal_places=3, verbose_name='объем')

    def __str__(self):
        if self.value < 1:
            return str(self.value.normalize())
        else:
            return str(int(self.value))
    class Meta:
        verbose_name = 'Объем'
        verbose_name_plural = 'Объемы'

    objects = models.Manager()
    my_objects = VolumeNormManager()

class PackageType(models.Model):
    name = models.CharField(max_length=150, verbose_name='тип упаковки')

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Тип упаковки'
        verbose_name_plural = 'Типы упаковок'


class Country(models.Model):
    name = models.CharField(max_length=150, verbose_name='страна')

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Discount(models.Model):
    value = models.PositiveSmallIntegerField(default=5, verbose_name='скидка')

    def __str__(self):
        return str(self.value)+'%'
    
    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='категория')
    slug = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    
    def get_absolute_url(self):
        return reverse('store:category', kwargs={'category_slug': self.slug})


class Item(models.Model):
    name = models.CharField(max_length=150, verbose_name='название', db_index=True)
    slug = models.SlugField(max_length=150, unique=True)
    description = models.TextField(verbose_name='описание', null=True, blank=True)
    stock = models.PositiveSmallIntegerField(default=0, verbose_name='количество на складе')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='цена')
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='бренд')
    beer_style = models.ForeignKey(BeerStyle, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='стиль напитка')
    volume = models.ForeignKey(Volume, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='объем')
    package_type = models.ForeignKey(PackageType, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='тип упаковки')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='страна')
    discount = models.ForeignKey(Discount, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='скидка')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name='категория')
    img = models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='изображение', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='изменено')

    def __str__(self):
        return f'{self.name} Количество - {self.stock}'

    class Meta:
        ordering = ('name',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    
    def get_absolute_url(self):
        return reverse('store:item', kwargs={'item_slug': self.slug})

    def sell_price(self):
        if self.discount:
            return round(float(self.price) - float(self.price)*self.discount.value/100, 2)
        return self.price

store/views.py
from django.shortcuts import redirect, render
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from store.utils import q_search
from store.models import Item
from store.filters import MyModelFilter

# Create your views here.
def show_item(request, item_slug):
    item = get_object_or_404(Item, slug=item_slug)
    context = {'item': item}
    return render(request, 'store/item.html', context)


class StoreListView(ListView):
    context_object_name = 'items'
    queryset = Item.objects.order_by('name')
    template_name = 'store/store.html'
    paginate_by = 5


class CategoryListView(ListView):
    context_object_name = 'items'
    template_name = 'store/category.html'
    paginate_by = 4
    
    def get_queryset(self):
        query = self.request.GET.get('q', None)
        if query:
            goods = q_search(query)
            if goods:
                self.my_filters = MyModelFilter(self.request.GET, queryset=goods)
                return self.my_filters.qs
            self.my_filters = MyModelFilter(self.request.GET, queryset=Item.objects.filter(id=-5))
            return self.my_filters.qs
        if self.kwargs:
            self.category_slug = self.kwargs.get("category_slug", None)
            if self.category_slug:
                queryset = Item.objects.filter(category__slug=self.category_slug)
                self.my_filters = MyModelFilter(self.request.GET, queryset=queryset)
                return self.my_filters.qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.my_filters and len(self.my_filters.qs) != 0:
            context['form'] = self.my_filters.form
        elif self.my_filters and len(self.my_filters.qs) == 0:
            context['empty_search'] = 'Поиск не дал результатов'
        if self.kwargs:
            if self.category_slug:
                if self.my_filters:
                    context['category_name'] = self.category_slug
        return context
    

templates/store/category.html
{% extends 'store/index.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
{% endblock %}

{% block title %}
Категория: {{category_name}}
{% endblock title %}

{% block category %}
{% if empty_search %}
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-auto">    
        <h3>{{empty_search}}</h3>
    </div>
  </div>
</div>  
{% endif %}
{% endblock category %}

{% block filters %}

<form class="vertical-form" method="GET" {% if request.GET.q %} action="{% url 'store:search' %}"{% endif %}>
    {% if request.GET.q %}
        <input type="hidden" name="q" value="{{ request.GET.q }}">
    {% endif %}
    {{form.name.label}}
    {{form.name}}
    {{form.discount.label}}
    {{form.discount}}

    <div class="price-horizontal">
        <div class="price-label">{{form.price__gt.label}}</div>
        <div>{{form.price__gt}}</div>
        <div>{{form.price__lt}}</div>
    </div>
    <div class="drop-down">{{form.brand__name.label}}
        {{form.brand__name}}
    </div>
    {{form.beer_style__name.label}}
    {{form.beer_style__name}}

    <div>{{form.volume__value.label}}{% if form %}, л{% endif %}</div>
        {{ form.volume__value }}
    
    {{form.package_type__name.label}}
    {{form.package_type__name}}
    {{form.country__name.label}}
    {{form.country__name}}
    {% if form %}
    <input type="submit" value="Применить" class="btn-basecolor btn" />
    {% endif %}
</form>

{% endblock filters %}

templates/store/category_old.html
{% extends 'store/index.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
{% endblock %}

{% block title %}
Категория: {{category_name}}
{% endblock title %}

{% block filters %}

<form class="vertical-form" method="GET">
    {{form.name.label}}
    {{form.name}}
    {{form.discount.label}}
    {{form.discount}}

    <div class="price-horizontal">
        <div class="price-label">{{form.price__gt.label}}</div>
        <div>{{form.price__gt}}</div>
        <div>{{form.price__lt}}</div>
    </div>
    {{form.brand__name.label}}
    {{form.brand__name}}
    {{form.beer_style__name.label}}
    {{form.beer_style__name}}

    <div>{{form.volume__value.label}}, л</div>
        {{ form.volume__value }}
    
    {{form.package_type__name.label}}
    {{form.package_type__name}}
    {{form.country__name.label}}
    {{form.country__name}}
    <input type="submit" value="Submit" class="btn-basecolor btn" />
</form>

{% endblock filters %}

templates/store/empty_search.html
{% extends 'store/index.html' %}

{% block title %}
Поиск не дал результатов
{% endblock title%}

{% block category %}
<h3>Поиск не дал результатов</h3>
{% endblock category %}

templates/store/index.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}


{% block styles %}
{% endblock %}

{% load static %}

{% block title %}
{% endblock title %}

{% block notification %}
    {% include 'carts/notifications.html' %}
{% endblock %}

{% block category %}
{% endblock category %}

{% block filters %}
{% endblock filters %}


{% block content %}
<div class="row">
{% for item in items %}
    <div class="col">
        <div class="card my-2" style="width: 18rem;">
          <h5 class="card-title"> </h5>
              <a href="{{item.get_absolute_url}}"><div class="row d-flex justify-content-center align-content-center">
                  <img class="card-img-top" src={{item.img.url}} alt="Card image cap" width=""></div></a>
          <div class="card-body">
            <h5 class="card-title">{{item.name}}</h5>
            <p class="card-text">объем {{item.volume.value.normalize}}л</p>
              <p class="card-text"><h3>{{item.price.normalize}}руб</h3></p>
            <a href="{% url 'cart:cart_add' %}" class="btn btn-basecolor c-w add-to-cart"
            data-product-id="{{item.id}}">
                {% csrf_token %}
                Добавить в корзину</a>
          </div>
        </div>
    </div>
{% endfor %}
{% endblock content %}
{% block paginator %}

{% if page_obj.has_other_pages %}
<nav>
    <ul class="paginator list-unstyled">
        {% if page_obj.has_previous %}
            <li class="page-num m-1">
            <a class="text-decoration-none" href="?{% change_params page=page %}{{ page_obj.previous_page_number }}">&lt;</a>
            </li>
        {% endif %}

        {% for page in paginator.page_range %}
        {% if page_obj.number == page %}
        <li class="page-num page-num-selected m-1">{{ page }}</li>
        {% else %}
            <li class="paginator-pages m-1">
            <a class="text-decoration-none" href="?{% change_params page=page %}">{{ page }} </a>
            </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-num m-1">
            <a class="text-decoration-none" href="?{% change_params page=page %}{{ page_obj.next_page_number }}">&gt;</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock paginator %}

templates/store/index_pagination_my_attempt.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% endblock title %}

{% block category %}
{% endblock category %}

{% block filters %}
{% endblock filters %}


{% block content %}
<div class="row">
{% for item in items %}
    <div class="col">
        <div class="card my-2" style="width: 18rem;">
          <h5 class="card-title"> </h5>
              <a href="{{item.get_absolute_url}}"><div class="row d-flex justify-content-center align-content-center">
                  <img class="card-img-top" src={{item.img.url}} alt="Card image cap" width=""></div></a>
          <div class="card-body">
            <h5 class="card-title">{{item.name}}</h5>
            <p class="card-text">объем {{item.volume.value.normalize}}л</p>
              <p class="card-text"><h3>{{item.price.normalize}}руб</h3></p>
            <a href="/basket/add{{item.get_absolute_url}}" class="btn btn-basecolor c-w">Добавить в корзину</a>
          </div>
        </div>
    </div>
{% endfor %}
{% endblock content %}
{% block paginator %}

{% if page_obj.has_other_pages %}
<nav>
    <ul class="paginator list-unstyled">
        {% if page_obj.has_previous %}
            {% if "?name" in request.get_full_path %}
            <li class="page-num m-1">
            <a class="text-decoration-none" href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">&lt;</a>
            </li>
            {% else %}
            <li class="page-num m-1">
            <a class="text-decoration-none" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
            </li>
            {% endif %}
        {% endif %}

        {% for page in paginator.page_range %}
        {% if page_obj.number == page %}
        <li class="page-num page-num-selected m-1">{{ page }}</li>
        {% else %}
            {% if "?name" in request.get_full_path %}
            <li class="paginator-pages m-1">
            <a class="text-decoration-none" href="{{ request.get_full_path }}&page={{ page }}">{{ page }} </a>
            </li>
            {% else %}
            <li class="paginator-pages m-1">
            <a class="text-decoration-none" href="?page={{ page }}">{{ page }} </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-num m-1">
            <a class="text-decoration-none" href="?page={{ page_obj.next_page_number }}">&gt;</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock paginator %}

templates/store/item.html
<!-- контроллер store.views.show_item передает в этот шаблон {'item': item, 'basket_sum': basket_sum} -->

{% extends 'base.html' %}

{% block title %}
    Продукт: {{item}}
{% endblock title %}

{% block content %}
<div class="beer_title" style="display: flex; justify-content: center;"><div><h3>{{item}}</h3></div></div>
    <div class="row m-5">
        <div class="col-md-3">
            <img src={{item.img.url}} width="50%"/>
        </div>
        <div class="col-md-9">
            <p>Бренд: {{item.brand.name}}</p>
            <p>Стиль: {{item.beer_style.name}}</p>
            <p>Объем: {{item.volume.value.normalize}}л</p>
            <p>Тип упаковки: {{item.package_type.name}}</p>
            <p>Страна: {{item.country.name}}</p>
            <p>Категория: {{item.category.name}}</p>
            <p>Скидка: {{item.discount.value}}%</p>
            <p>Количество на складе: {{item.stock}}</p>
            <p>Описание: {{item.description}}</p>
            <p>Цена: {{item.price.normalize}}руб</p>
        </div>
    </div>
    <div class="m-5">
        <div class="row d-flex justify-content-center align-content-center">
            <div><a href="{% url 'cart:cart_add' %}" class="btn btn-basecolor add-to-cart"
            data-product-id="{{item.id}}">
                {% csrf_token %}
                Добавить в корзину</a></div>
        </div>
    </div>
{% endblock content %}

{% block paginator %}
{% endblock paginator %}

templates/store/store.html
{% extends 'store/index.html' %}

{% block title %}
Главная страница магазина
{% endblock title %}