account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from account import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('simple/', views.simple_view, name='simple'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('activate/<uidb64>/<token>', views.ActivateAccountView.as_view(), name='activate'),
    path('users-cart/', views.users_cart, name='users_cart')

]

beerproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store'),),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),


    path('reset_password/', PasswordResetView.as_view(
        html_email_template_name = 'register/password_reset_email_msg.html',
        subject_template_name = 'register/password_reset_subject_msg.txt'
    ), name='reset_password'),
    path('reset_password_sent/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carts/urls.py
from django.urls import path
from carts import views

app_name = "carts"

urlpatterns = [
               path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
               path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
               path('cart_remove/', views.CartRemove.as_view(), name='cart_remove'),
               ]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'


urlpatterns = [
               path('create-order/', views.OrderCreateView.as_view(), name='create_order'),
               ]

orders/models.py
from django.db import models
from store.models import Item

from account.models import User
from phonenumber_field.modelfields import PhoneNumberField

class OrderitemQuery(models.QuerySet):

    def total_price(self):
        return sum(cart.item_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class OrderStatus(models.Model):
    IN_PROGRESS = 'В обработке'
    ISSUED = 'Выдан'
    CANCELED = 'Отменен'
    STATUS_CHOICES = [
        (IN_PROGRESS, 'В обработке'),
        (ISSUED, 'Выдан'),
        (CANCELED, 'Отменен')
    ]
    order_status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=IN_PROGRESS, verbose_name='Статус заказа')

    def __str__(self):
        return self.order_status
    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы Заказов'


class Order(models.Model):
    user = models.ForeignKey(User, models.SET_DEFAULT, blank=True, null=True, verbose_name='Пользователь', default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    phone_number = PhoneNumberField(max_length=16, verbose_name='Номер телефона')
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Состояние оплаты')
    status = models.ForeignKey(OrderStatus, on_delete=models.SET_DEFAULT, verbose_name='Статус заказа', default=1)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ № {self.pk} | Покупатель {self.user.email} {self.user.username if self.user.username else 'покупатель'}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    item = models.ForeignKey(Item, on_delete=models.SET_DEFAULT, null=True, blank=True, verbose_name='Продукт', default=None)
    name = models.CharField(max_length=150, verbose_name='Название')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    class Meta:
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданные товары'

    objects = OrderitemQuery.as_manager()

    def items_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f'Товар {self.name} | Заказ № {self.order.pk}'

orders/forms.py
import re

from django import forms


class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ('0', False),
            ('1', True)
        ],
    )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ('0', False),
            ('1', True)
        ],
    )

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError('Номер телефона должен содержать только цифры')

        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError('Неверный формат номера')

        return data

orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db import transaction
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView

from carts.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem


class OrderCreateView(LoginRequiredMixin, FormView):
    template_name = 'orders/create_order.html'
    form_class = CreateOrderForm
    success_url = reverse_lazy('account:simple')

    def get_initial(self):
        initial = super().get_initial()
        initial['first_name'] = self.request.user.username
        return initial

    def form_valid(self, form):
        try:
            with transaction.atomic():
                user = self.request.user
                cart_items = Cart.objects.filter(user=user)

                if cart_items.exists():
                    # Создаем заказ
                    order = Order.objects.create(
                        user=user,
                        phone_number=form.cleaned_data['phone_number'],
                        requires_delivery=form.cleaned_data['requires_delivery'],
                        delivery_address=form.cleaned_data['delivery_address'],
                        payment_on_get=form.cleaned_data['payment_on_get']
                    )
                    # Создаем OrderItem заказанных товаров
                    for cart_item in cart_items:
                        item = cart_item.item
                        name = cart_item.item.name
                        price = cart_item.item.sell_price()
                        quantity = cart_item.quantity

                        if item.stock < quantity:
                            raise ValidationError(f'Недостаточное количество товара {name}, в наличии - {item.stock}')

                        OrderItem.objects.create(
                            order=order,
                            item=item,
                            name=name,
                            price=price,
                            quantity=quantity,
                        )
                        item.stock -= quantity
                        item.save()
                    # Очищаем корзину пользователя после создания заказа
                    cart_items.delete()

                    messages.success(self.request, 'Заказ оформлен!')
                    return redirect('account:simple')
        except ValidationError as e:
            messages.warning(self.request, str(e))
            return redirect('carts:order')

    def form_invalid(self, form):
        messages.error(self.request, 'Заполните все обязательные поля!')
        return redirect('orders:create_order')

templates/orders/create_order.html
{% extends 'carts/base_basket.html' %}
{% load static %}
{% load carts_tags %}


    {% block title %}
    Оформление заказа
    {% endblock title %}


    {% block styles %}
         <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    {% endblock %}

            {% block heading %}
            <div class="flexbox1">
                <div><h1>Оформление заказа</h1></div>
                <div><a href="{% url 'account:users_cart' %}" style="color: #FFF;"><h4>КОРЗИНА</h4></a></div>
            </div>
            {% endblock heading %}

        {% block content %}
        {% user_carts request as carts %}
        <div class="order_items">
            {% for cart in carts %}
            <div><h3>{{cart.item.name}} - {{cart.item.sell_price}}руб - {{cart.quantity}}шт</h3></div>
            {% endfor %}
            <div><h2>Сумма заказа: {{carts.total_price}}руб</h2></div>
        </div>
        <!--<div class="form">
            <form method="POST" action="">
                {% csrf_token %}
                    {{ form.as_p }}
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <input class="btn btn-basecolor" type="submit" value="Разместить">
            </form>
        </div>-->
        <div class="container">
                            <h3 class="text-center">Детали заказа</h3>
                            <div class="card mb-3">
                                <div class="card-body">
                                    <form action="{% url 'orders:create_order' %}" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="id_first_name" class="form-label">Имя*:</label>
                                                <input type="text" class="form-control" id="id_first_name"
                                                    value="{% if form.first_name.value%}{{form.first_name.value}}{% endif %}"
                                                    name="first_name" required>
                                                {% if form.first_name.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <!--<div class="col-md-6 mb-3">
                                                <label for="id_last_name" class="form-label">Фамилия*:</label>
                                                <input type="text" class="form-control" id="id_last_name" name="last_name" required>
                                            </div>-->
                                            <div class="col-md-6 mb-3"> </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_phone_number" class="form-label">Номер телефона*:</label>
                                                <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                                    value="{% if form.phone_number.value%}{{form.phone_number.value}}{% endif %}"
                                                    placeholder="В формате: XXX-XXX-XX-XX"
                                                    required>
                                                {% if form.phone_number.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <div>
                                                <label for="id_requires_delivery" class="form-label">Способ доставки: </label>
                                                </div>
                                                    <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                                        id="id_requires_delivery" value="1" checked>
                                                    <label class="form-check-label" for="id_requires_delivery">Нужна
                                                        доставка</label>
                                                </div>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                                        id="id_requires_delivery" value="0">
                                                    <label class="form-check-label" for="id_requires_delivery">Самовывоз</label>
                                                </div>
                                            </div>
                                            <div class="mb-3" id="deliveryAddressField">
                                                <label for="id_delivery_address" class="form-label">Адрес
                                                    доставки*:</label>
                                                <textarea class="form-control" id="id_delivery_address"
                                                    name="delivery_address" rows="2"></textarea>
                                                {% if form.delivery_address.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.delivery_address.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <div>
                                                <label class="form-label">Способ оплаты: </label>
                                                </div>
                                                    <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                                        id="id_payment_on_get" value="0" checked>
                                                    <label class="form-check-label" for="id_payment_on_get">Оплата
                                                        картой</label>
                                                </div>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                                        id="id_payment_on_get" value="1">
                                                    <label class="form-check-label" for="id_payment_on_get">Наличными/картой
                                                        при получении</label>
                                                    {% if form.payment_on_get.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.payment_on_get.errors}}</div>
                                                {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-basecolor">Оформить заказ</button>
                                    </form>
                                </div>
                            </div>
                        </div>
        <div class="go_main"><a href="/"><h3>На главную</h3></a></div>
        </div>
        {% endblock content %}